project_name: jetstream

release:
  github:
    owner: nats-io
    name: jetstream
  name_template: "Release {{.Tag}}"
  draft: true

changelog:
  skip: true

builds:
  - main: ./nats
    id: nats
    binary: nats
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE

dockers:
  - goos: linux
    goarch: amd64
    skip_push: true
    binaries:
      - nats
    image_templates:
      - synadia/jsm:{{.Version}}
      - synadia/jsm:nightly
    extra_files:
      - README.md
      - ngs-server.conf
      - entrypoint.sh

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

snapshot:
  name_template: 'nightly-{{ time "20060201" }}'
